version: 2
jobs:
  build:
    working_directory: ~/jocker
    docker:
      - image: maven:3.3-jdk-8
    steps:
      - checkout
      - restore_cache:
          key: jocker-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: jocker-{{ checksum "pom.xml" }}

      - setup_remote_docker
      - run:
          command: mvn install
